[package]
name = "sl-sh"
version = "0.8.33"
authors = ["Steven Stanfield <stanfield@scarecrowtech.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redox_liner = { git = "https://github.com/sstanfield/liner.git" }
#redox_liner = { path = "../liner" }
#broom = { git = "https://github.com/sstanfield/broom.git" }
broom = { path = "../broom" }
glob = "0.3"
nix = "0.15.0"
libc = "0.2"
# jemallocator = "0.3.0"

[build-dependencies]
chrono = "0.4.7"

[profile.release]
lto = true
#opt-level = 'z'
#debug = true

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "start_benchmark"
harness = false

[[bench]]
name = "start_script"
harness = false

